#cloud-config
system_info:
  default_user:
    name: k8s
    lock_passwd: true
    gecos: Kubernetes Interactive User
    groups: [wheel, adm, systemd-journal]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
chpasswd:
  list: |
    k8s:pass123456
  expire: False
